name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install -g clean-css-cli
          npm install -g uglify-js

      - name: Build
        run: |
          mkdir -p dist
          cp -r *.html dist/
          cp -r css dist/
          cp -r js dist/
          cp -r components dist/
          cp -r images dist/ 2>/dev/null || :

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist